# Generated by Django 5.1.2 on 2025-09-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='device_info',
            field=models.JSONField(blank=True, help_text='Store device information for mobile payments', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='platform',
            field=models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('api', 'API')], default='web', max_length=20),
        ),
    ]
