# Generated by Django 5.1.2 on 2025-12-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_device_info_payment_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='phonepe_order_id',
            field=models.CharField(blank=True, help_text="PhonePe's Merchant Reference ID (order_id from PhonePe response)", max_length=100, null=True),
        ),
    ]
