# Generated by Django 5.1.2 on 2026-01-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_phonepe_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='phonepe_order_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Gateway-specific ID (PhonePe order_id or Cashfree cf_link_id)', max_length=100, null=True),
        ),
    ]
