# Generated by Django 5.1.2 on 2026-01-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_payment_phonepe_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_gateway',
            field=models.CharField(blank=True, choices=[('Cashfree', 'Cashfree'), ('PhonePe', 'PhonePe')], default='Cashfree', max_length=50, null=True),
        ),
    ]
