# Generated by Django 5.1.2 on 2025-03-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('brand', 'Brand'), ('seller', 'Seller'), ('manufacturer', 'Manufacturer'), ('packager', 'Packager')], help_text='Specify the type of entity.', max_length=255),
        ),
    ]
