# Generated by Django 5.1.2 on 2025-01-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_estore'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('', ''), ('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=255, null=True),
        ),
    ]
