# Generated by Django 5.1.2 on 2025-07-15 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estores', '0001_initial'),
        ('users', '0004_entity_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='estore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estore_entities', to='estores.estore'),
        ),
    ]
