# Generated by Django 5.1.2 on 2025-02-03 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_shippingaddress_mobile_shippingaddress_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_entities', to=settings.AUTH_USER_MODEL),
        ),
    ]
