# Generated by Django 5.1.2 on 2025-02-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_entity_details_entity_website_alter_entity_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
