# Generated by Django 5.1.2 on 2025-02-21 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_google_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id']},
        ),
    ]
