# Generated by Django 5.1.2 on 2025-02-27 05:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_entity_options_alter_shippingaddress_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
