# Generated by Django 5.1.2 on 2025-02-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxcategory',
            name='rate',
        ),
        migrations.AddField(
            model_name='taxcategory',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='taxcategory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='taxcategory',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxcategory',
            name='igst_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='taxcategory',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='taxcategory',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
