# Generated by Django 5.1.2 on 2025-02-21 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxations', '0002_remove_taxcategory_rate_taxcategory_cgst_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxcategory',
            options={'ordering': ['-id']},
        ),
    ]
