# Generated by Django 5.1.2 on 2025-01-26 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
        ('estores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='estore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estore_blogs', to='estores.estore'),
        ),
        migrations.AddField(
            model_name='tag',
            name='estore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estore_tags', to='estores.estore'),
        ),
    ]
