# Generated by Django 5.1.2 on 2025-04-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('product', 'Product Specific'), ('cart', 'Cart Wide')], max_length=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('buy_x_get_y', 'Buy X Get Y'), ('bundle', 'Bundle Offer'), ('discount', 'Direct Discount')], max_length=20),
        ),
    ]
