# Generated by Django 5.1.2 on 2025-04-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='min_cart_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_scope',
            field=models.CharField(choices=[('cart', 'Cart Wide'), ('product', 'Product Specific')], default='product', max_length=10),
        ),
    ]
