# Generated by Django 5.1.2 on 2025-02-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estore',
            options={'ordering': ['-id']},
        ),
    ]
