# Generated by Django 5.1.2 on 2025-04-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypin',
            name='pin_code',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
