# Generated by Django 5.1.2 on 2025-08-07 11:54

import django.db.models.deletion
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Is this email send credential active?')),
                ('host', models.CharField(help_text='SMTP host for sending emails', max_length=255)),
                ('email', models.EmailField(help_text='Email address used for sending emails', max_length=255)),
                ('password', encrypted_fields.fields.EncryptedCharField(help_text='Password for the email account', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('estore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estore_email_send_credentials', to='estores.estore')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ShipCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Is this credential active?')),
                ('name', models.CharField(help_text='Name of the service example - ShipRocket, Delhivery, etc.', max_length=100)),
                ('email', models.EmailField(help_text='Email associated with account', max_length=255)),
                ('password', encrypted_fields.fields.EncryptedCharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('estore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estore_shiprocket_credentials', to='estores.estore')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Is this WhatsApp credential active?')),
                ('sender_name', models.CharField(help_text='Name of the sender', max_length=100)),
                ('sender_number', models.CharField(max_length=15)),
                ('auth_id', models.CharField(max_length=100)),
                ('auth_token', encrypted_fields.fields.EncryptedCharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('estore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estore_whatsapp_credentials', to='estores.estore')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
