# Generated by Django 5.1.2 on 2025-08-07 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estores', '0002_emailcredential_shipcredential_whatsappcredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcredential',
            name='templates',
            field=models.JSONField(blank=True, default=dict, help_text="Templates for WhatsApp messages in JSON format. Example: {'key': 'template_name', ...}", null=True),
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('estore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estore_static_pages', to='estores.estore')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
