# Generated by Django 5.1.2 on 2025-02-27 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estores', '0002_alter_estore_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_code', models.CharField(max_length=10)),
                ('city', models.CharField(blank=True, help_text='City associated with the PIN code', max_length=100, null=True)),
                ('state', models.CharField(blank=True, help_text='State associated with the PIN code', max_length=100, null=True)),
                ('cod_available', models.BooleanField(default=True, help_text='Is cash on delivery available for this PIN?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('estore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estore_delivery_pins', to='estores.estore')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('estore', 'pin_code')},
            },
        ),
    ]
