# Generated by Django 5.1.2 on 2025-08-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estores', '0003_whatsappcredential_templates_staticpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
