# Generated by Django 5.1.2 on 2025-08-08 07:50

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estores', '0004_staticpage_meta_description_staticpage_meta_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='estore',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the store', null=True),
        ),
        migrations.AddField(
            model_name='estore',
            name='favicon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='favicon'),
        ),
        migrations.AddField(
            model_name='estore',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='icon_image'),
        ),
        migrations.AddField(
            model_name='estore',
            name='mobile',
            field=models.CharField(blank=True, help_text='Mobile number for the store', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='estore',
            name='social_accounts',
            field=models.JSONField(blank=True, default=dict, help_text="Social media accounts in JSON format. Example: {'facebook': 'https://facebook.com/store', 'instagram': 'https://instagram.com/store'}", null=True),
        ),
        migrations.AddField(
            model_name='estore',
            name='tagline',
            field=models.CharField(blank=True, help_text='Tagline for the store', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='estore',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo_image'),
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('estore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estore_static_pages', to='estores.estore')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='StaticPage',
        ),
    ]
