# Generated by Django 5.1.2 on 2025-03-04 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estores', '0001_initial'),
        ('products', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=24, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total price of all items including taxes and discounts', max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'pending'), ('paid', 'paid')], default='pending', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product_listing_count', models.PositiveIntegerField(default=0)),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('estore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estore_orders', to='estores.estore')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.shippingaddress')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('ready_for_delivery', 'Ready for Delivery'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='ready_for_delivery', max_length=50)),
                ('product_listing_count', models.PositiveIntegerField(default=0, help_text='Number of distinct products in this package')),
                ('total_units', models.PositiveIntegerField(default=0, help_text='Total number of items in this package')),
                ('delivery_out_date', models.DateTimeField(blank=True, null=True)),
                ('delivered_date', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('delivery_executive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='de_packages', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='orders.order')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Number of units ordered for this product')),
                ('status', models.CharField(choices=[('order_placed', 'order_placed'), ('shipped', 'shipped'), ('ready_for_delivery', 'Ready for Delivery'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'delivered'), ('canceled', 'canceled')], default='order_placed', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of purchase', max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Total price for this product line (quantity × unit_price)', max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('shipped_date', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
                ('product_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_listing_order_items', to='products.productlisting')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='Number of units included in this package')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item_package_item', to='orders.orderitem')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_items', to='orders.deliverypackage')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
