# Generated by Django 5.1.2 on 2025-02-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_created_orderitem_status_orderitem_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_items',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
