# Generated by Django 5.1.2 on 2025-06-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_deliverypackage_is_return_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='review_added',
            field=models.BooleanField(default=False),
        ),
    ]
