# Generated by Django 5.1.2 on 2025-06-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_review_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Delivery Charges if aplicable', max_digits=10),
        ),
    ]
