# Generated by Django 5.1.2 on 2025-02-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_rename_order_id_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, help_text='Number of units included in this package'),
        ),
    ]
