# Generated by Django 5.1.2 on 2025-02-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_packageitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverypackage',
            name='status',
            field=models.CharField(choices=[('ready_for_delivery', 'Ready for Delivery'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='ready_for_delivery', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('shipped', 'shipped'), ('ready_for_delivery', 'Ready for Delivery'), ('delivered', 'delivered'), ('canceled', 'canceled')], default='pending', max_length=50),
        ),
    ]
