# Generated by Django 5.1.2 on 2025-02-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_shipped_date_deliverypackage_delivery_out_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverypackage',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='packageitem',
            options={'ordering': ['-id']},
        ),
    ]
