# Generated by Django 5.1.2 on 2025-02-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_deliverypackage_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='shipped_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'pending'), ('paid', 'paid')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('order_placed', 'order_placed'), ('shipped', 'shipped'), ('ready_for_delivery', 'Ready for Delivery'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'delivered'), ('canceled', 'canceled')], default='order_placed', max_length=50),
        ),
    ]
