# Generated by Django 5.1.2 on 2025-08-07 11:55

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=encrypted_fields.fields.EncryptedCharField(editable=False, max_length=64, unique=True),
        ),
    ]
