# Generated by Django 5.1.2 on 2024-12-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productlisting',
            options={'ordering': ['-id']},
        ),
    ]
