# Generated by Django 5.1.2 on 2025-03-05 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnExchangePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Policy name (e.g., '7-day return')", max_length=100)),
                ('return_available', models.BooleanField(default=False)),
                ('exchange_available', models.BooleanField(default=False)),
                ('return_days', models.PositiveIntegerField(blank=True, help_text='Number of days allowed for return', null=True)),
                ('exchange_days', models.PositiveIntegerField(blank=True, help_text='Number of days allowed for exchange', null=True)),
                ('conditions', models.TextField(blank=True, help_text='Conditions for return/exchange', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='productlisting',
            name='return_exchange_policy',
            field=models.ForeignKey(blank=True, help_text='Return and exchange policy for this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_listings', to='products.returnexchangepolicy'),
        ),
    ]
