# Generated by Django 5.1.2 on 2024-12-28 14:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productlisting_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='main_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
