# Generated by Django 5.1.2 on 2025-03-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_returnexchangepolicy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('product', 'Product'), ('blog', 'Blog')], default='product', help_text='Specify if the category is for a product or a blog.', max_length=10),
        ),
    ]
