# Generated by Django 5.1.2 on 2025-01-16 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productlisting_main_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='listing',
            new_name='product_listing',
        ),
    ]
