# Generated by Django 5.1.2 on 2025-04-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_category_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='review_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
