# Generated by Django 5.1.2 on 2025-06-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productlisting_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='is_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('product', 'Product'), ('blog', 'Blog'), ('service', 'Service')], default='product', help_text='Specify if the category is for a product or a blog.', max_length=10),
        ),
    ]
