# Generated by Django 5.1.2 on 2025-01-26 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estores', '0001_initial'),
        ('products', '0005_rename_listing_productlistingimage_product_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='estore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estore_categories', to='estores.estore'),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='estore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estore_product_listings', to='estores.estore'),
        ),
    ]
