# Generated by Django 5.1.2 on 2025-07-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_category_options_category_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_unit',
            field=models.CharField(default='', help_text='Unit of measurement (e.g., ml, g)', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_size',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Size of a single unit (e.g., 200.5)', max_digits=10),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='size_unit',
            field=models.CharField(blank=True, help_text='Total unit of measure (e.g., ml)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='total_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total size (e.g., 600.75)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='units_per_pack',
            field=models.PositiveIntegerField(default=1, help_text='Number of units in the pack (e.g., 3)'),
        ),
    ]
