# Generated by Django 5.1.2 on 2025-02-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_category_estore_productlisting_estore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlisting',
            name='listed',
        ),
        migrations.AddField(
            model_name='productlisting',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
