# Generated by Django 5.1.2 on 2025-07-05 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_size_unit_product_unit_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlisting',
            old_name='total_size',
            new_name='unit_size',
        ),
    ]
