# Generated by Django 5.1.2 on 2025-02-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='review_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
