# Generated by Django 5.1.2 on 2025-07-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_total_size_productlisting_unit_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='attributes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
