# Generated by Django 5.1.2 on 2025-11-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_variant_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='attributes',
            field=models.JSONField(blank=True, help_text="Example -> [ {'name':'color', 'value':'Red', 'real_value':'#ff0000'}, {'name':'storage', 'value':'128GB', 'real_value':'128'}]", null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='name',
            field=models.CharField(help_text="Example: 'Red, 128GB', 'Pack of 3'", max_length=255),
        ),
    ]
