# Generated by Django 5.1.2 on 2025-02-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productlisting_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=5, max_digits=4, null=True),
        ),
    ]
