# Generated by Django 5.1.2 on 2025-11-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_variant_attributes_alter_variant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size_unit',
            field=models.CharField(blank=True, default='', help_text='Unit of measurement (e.g., ml, g)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_size',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, help_text='Size of a single unit (e.g., 200.5)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='variant',
            name='attributes',
            field=models.JSONField(blank=True, help_text='Example -> [ {"name":"color", "value":"Red", "real_value":"#ff0000"}, {"name":"storage", "value":"128GB", "real_value":"128"}]', null=True),
        ),
    ]
