# Generated by Django 5.1.2 on 2025-02-10 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productlisting_rating'),
        ('taxations', '0002_remove_taxcategory_rate_taxcategory_cgst_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_category_products', to='taxations.taxcategory'),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='approved',
            field=models.BooleanField(default=False, help_text='Product_listing will be shown on the website/app'),
        ),
    ]
