# Generated by Django 5.1.2 on 2025-12-25 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_size_unit_alter_product_unit_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='make_id',
            field=models.CharField(blank=True, help_text='Product identification code (e.g., SKU, UPC)', max_length=100, null=True),
        ),
    ]
