# Generated by Django 5.1.2 on 2025-02-12 13:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_tax_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlistingimage',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
