# Generated by Django 5.1.2 on 2025-02-21 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_productlistingimage_image'),
        ('taxations', '0003_alter_taxcategory_options'),
        ('users', '0007_alter_entity_options_alter_shippingaddress_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='productlistingimage',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_products', to='users.entity'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_products', to='products.category'),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='buy_limit',
            field=models.PositiveIntegerField(default=10, help_text='Maximum limit for this product in an order'),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='tax_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_category_product_listings', to='taxations.taxcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_product_listings', to='products.category'),
        ),
    ]
