# Generated by Django 5.1.2 on 2025-02-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_category_options_alter_feature_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
